# Generated by Django 2.2.14 on 2022-11-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221128_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
