# Generated by Django 2.2.14 on 2022-11-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_colors_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Products',
        ),
    ]
