# Generated by Django 4.1.3 on 2022-12-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='trx_ref',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
