# Generated by Django 4.1.3 on 2022-12-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_payment_trx_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(blank=True, to='core.colors'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='colors',
            field=models.ManyToManyField(blank=True, to='core.size'),
        ),
    ]
