# Generated by Django 4.1.3 on 2022-12-04 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_size_alter_products_colors_orderitem_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='colors',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.size'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(blank=True, to='core.size'),
        ),
    ]
