# Generated by Django 4.1.3 on 2022-12-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_orderitem_colors_orderitem_size_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='symbol',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
