# Generated by Django 4.1.3 on 2023-02-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_products_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DS', 'Dispatched'), ('IT', 'In transit'), ('DL', 'Delivered'), ('DSO', 'Dispatching soon')], default='DSO', max_length=3),
        ),
    ]
