# Generated by Django 4.1.3 on 2023-03-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(to='core.size'),
        ),
    ]
