# Generated by Django 4.1.3 on 2023-05-19 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_products_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Variant_color', to='core.colors')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Variant_product', to='core.products')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Variant_size', to='core.size')),
            ],
        ),
    ]
