# Generated by Django 4.1.3 on 2023-05-20 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_orderitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
