# Generated by Django 2.2.14 on 2022-11-28 00:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221128_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
