# Generated by Django 2.2.14 on 2022-11-28 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221128_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='doctors',
            new_name='colors',
        ),
    ]
