# Generated by Django 2.2.14 on 2022-11-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
