# Generated by Django 4.1.3 on 2022-12-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='trx_ref',
        ),
    ]
