# Generated by Django 4.1.3 on 2022-12-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_stripe_charge_id_payment_trx_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
